[package]
name = "rsvalidity"
version = "0.1.0"
authors = ["raw-bacon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
